<a href="https://colab.research.google.com/github/Z-9000/ML-DL_with_TensorFlow/blob/Code-with-Google-Collab/00Tensorflow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Starting with the basics of the tensorflow.**


*   Intro to tensors
*   Getting info from tensors
*   Manipulating tensors
*   Tensors & NumPy
*   Using @tf.function (a way to speed up your regular python functions)
*   Using GPUs with TensorFlow(or TPUs)
*   Exercise









In [1]:
import tensorflow as tf
print(tf.__version__)

2.19.0


# Creating tensors with tf.constant()

In [2]:
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [3]:
scalar.ndim

0

In [4]:
vector = tf.constant([10, 10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [5]:
vector.ndim

1

In [6]:
matrix = tf.constant([[10, 7],
                      [7, 10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [7]:
matrix.ndim

2

In [8]:
another_matrix = tf.constant([[10., 7.],
                              [3.,2.],
                              [8.,9.]], dtype=tf.float16)
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [9]:
another_matrix.ndim

2

In [10]:
tensor = tf.constant([[[1,2,3],
                      [4,5,6]],
                      [[7,8,9],
                      [10,11,12]],
                      [[13,14,15],
                      [16,17,18]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [11]:
tensor.ndim

3

scalar : a single number
vector : a number with direction
matrix : a 2d array of numbers
tensor : an n-dimensional array of numbers(where n can be any number, a 0-dim tensor is a scalar, a 1-dim tensor is a vector)